---
apiVersion: v2
name: microservice
version: 0.1.0
appVersion: 1.1.0
description: A Helm chart which provide a DRY microservice deployment mechanism
source:
  - https://github.com/mallinath2015/helm-project
